"""empty message

Revision ID: 917959546712
Revises: 
Create Date: 2024-09-06 08:16:54.591850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917959546712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
